#!/usr/bin/env node
import { readFileSync, readdirSync, existsSync, cpSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { RECIPES, type Recipe } from "./recipes.js";
import {
  loadProject,
  ensureProvider,
  ensureImport,
  addDependency,
  addDevDependency,
  savePkg,
  save,
  type ProjectInfo,
} from "./project.js";
import { c, step, ok, warn, fail, unifiedDiff } from "./util.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const SDK_VERSION = "^0.1.0";

function help() {
  console.log(`
${c.bold("midzap")} — turn an existing web2 React app into a Midnight privacy app.

${c.bold("Usage")}
  npx @midzap/cli add <recipe> [dir]   apply a recipe (default dir: .)
  npx @midzap/cli list                 show recipes
  npx @midzap/cli doctor [dir]         check an integrated project

${c.bold("Options")}
  --dry-run    print the changes, write nothing
  --yes, -y    skip the confirmation prompt

${c.bold("Recipes")}
${Object.values(RECIPES).map((r) => `  ${c.cyan(r.id.padEnd(18))} ${r.title}`).join("\n")}

${c.bold("Example")}
  npx @midzap/cli add age-gate ./my-shop --dry-run
`);
}

function tsxFiles(root: string): string[] {
  const out: string[] = [];
  const walk = (dir: string, depth: number) => {
    if (depth > 3 || !existsSync(dir)) return;
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      if (e.name === "node_modules" || e.name.startsWith(".")) continue;
      const p = join(dir, e.name);
      if (e.isDirectory()) walk(p, depth + 1);
      else if (/\.(tsx|jsx)$/.test(e.name)) out.push(p);
    }
  };
  walk(join(root, "src"), 0);
  if (out.length === 0) walk(root, 0);
  return out;
}

function circuitSource(circuit: string): string | null {
  for (const base of [join(HERE, "..", "recipes", "managed"), join(HERE, "..", "..", "..", "examples")]) {
    const direct = join(base, circuit);
    if (existsSync(join(direct, "contract", "index.js"))) return direct;
    // monorepo layout: examples/<app>/src/managed/<circuit>
    if (existsSync(base)) {
      for (const app of readdirSync(base)) {
        const p = join(base, app, "src", "managed", circuit);
        if (existsSync(join(p, "contract", "index.js"))) return p;
      }
    }
  }
  return null;
}

const WS_SHIM = `// Browser shim for \`isomorphic-ws\` — the midnight-js indexer provider
// imports { WebSocket } from it, but its browser build has no named export.
const WS = (globalThis as unknown as { WebSocket: typeof WebSocket }).WebSocket;
export default WS;
export { WS as WebSocket };
`;

const EXCLUDE = [
  "@midzap/sdk",
  "@midnight-ntwrk/compact-runtime",
  "@midnightntwrk/onchain-runtime-v4",
  "@midnight-ntwrk/midnight-js-contracts",
  "@midnight-ntwrk/midnight-js-types",
  "@midnight-ntwrk/midnight-js-level-private-state-provider",
  "@midnight-ntwrk/midnight-js-indexer-public-data-provider",
  "@midnight-ntwrk/midnight-js-http-client-proof-provider",
  "@midnight-ntwrk/midnight-js-fetch-zk-config-provider",
  "@midnight-ntwrk/dapp-connector-api",
];

function midnightViteConfig(port?: string): string {
  return `import { defineConfig } from "vite";
import { fileURLToPath } from "node:url";
import react from "@vitejs/plugin-react";
import wasm from "vite-plugin-wasm";
import { nodePolyfills } from "vite-plugin-node-polyfills";

// Generated by \`midzap add\`. Bundling the @midnight-ntwrk live stack needs
// WASM support, Node builtin shims, a real WebSocket for isomorphic-ws, and
// the WASM packages kept out of the esbuild pre-bundler. \`esnext\` targets
// give native top-level await.
export default defineConfig({
  plugins: [wasm(), nodePolyfills(), react()],${port ? `\n  server: { port: ${port} },` : ""}
  resolve: {
    alias: {
      "isomorphic-ws": fileURLToPath(new URL("./src/ws-shim.ts", import.meta.url)),
    },
  },
  optimizeDeps: { exclude: ${JSON.stringify(EXCLUDE, null, 6).replace(/\n {6}/g, "\n      ").replace(/\n {4}]/, "\n    ]")} },
  build: { target: "esnext" },
  esbuild: { target: "esnext" },
});
`;
}

/** Replace a stock Vite config with the Midnight-aware one. */
function patchVite(root: string): { path: string; before: string; after: string; shim: string } | null {
  const path = ["vite.config.ts", "vite.config.js", "vite.config.mjs"]
    .map((p) => join(root, p))
    .find(existsSync);
  if (!path) return null;
  const before = readFileSync(path, "utf8");
  if (/vite-plugin-wasm/.test(before)) return null;
  const port = before.match(/port:\s*(\d+)/)?.[1];
  return { path, before, after: midnightViteConfig(port), shim: join(root, "src", "ws-shim.ts") };
}

function midnightConfig(recipe: Recipe): string {
  const addrConst = `${recipe.predicateKind.toUpperCase().replace(/-/g, "_")}_CONTRACT_ADDRESS`;
  return `// Generated by @midzap/cli.
// See https://www.npmjs.com/package/@midzap/sdk
import { InMemoryProofBackend, type ContractBindings } from "@midzap/sdk";

export const ${addrConst} = "0xREPLACE_WITH_DEPLOYED_ADDRESS";

export const contracts: ContractBindings = {
  "${recipe.predicateKind}": {
    address: ${addrConst},
    // @ts-ignore -- generated circuit module
    load: () => import("./managed/${recipe.circuit}/contract/index.js"),
  },
};

// Until you've deployed the circuit and set the address above, this runs
// the predicate LOGIC in-browser so the integration is testable end to end.
// The vite.config.ts \`midzap add\` wrote already bundles the real Midnight
// runtime — set VITE_MZ_LIVE=1 to use it once you have a wallet + address.
const LIVE = Boolean((import.meta as unknown as { env?: Record<string, string> }).env?.VITE_MZ_LIVE);
export const backend = LIVE ? undefined : new InMemoryProofBackend();
`;
}

function add(recipeId: string, dir: string, opts: { dryRun: boolean; yes: boolean }) {
  const recipe = RECIPES[recipeId];
  if (!recipe) fail(`Unknown recipe "${recipeId}". Try: ${Object.keys(RECIPES).join(", ")}`);

  const info: ProjectInfo = loadProject(dir);
  step(`Project: ${c.dim(info.root)}`);

  // 1. find the file with the gate and rewrite it
  let target: { path: string; before: string; after: string; note: string } | null = null;
  for (const path of tsxFiles(info.root)) {
    const before = readFileSync(path, "utf8");
    const res = recipe.apply(before);
    if (res) {
      const withImport = ensureImport(res.text, "@midzap/sdk/react", recipe.imports);
      target = { path, before, after: withImport, note: res.note };
      break;
    }
  }
  if (!target) {
    fail(
      `No "${recipeId}" pattern found. This recipe looks for a self-reported control ` +
        `(checkbox / file input / real-name login) gating a button.`
    );
  }

  // 2. ensure the provider on the app root
  const rootBefore = readFileSync(info.rootFile, "utf8");
  const rootRes = ensureProvider(
    info.rootFile === target!.path ? target!.after : rootBefore,
    recipe.providerProps
  );
  if (info.rootFile === target!.path) target!.after = rootRes.text;

  // 3. generated files
  const cfgPath = join(info.root, "src", "midnight.ts");
  const cfgText = midnightConfig(recipe);
  const src = circuitSource(recipe.circuit);
  const vitePatch = patchVite(info.root);

  // 4. package.json deps
  const added = addDependency(info.pkg, "@midzap/sdk", SDK_VERSION);
  const viteDeps = vitePatch
    ? (["vite-plugin-wasm", "vite-plugin-node-polyfills"] as const).filter((d) => addDevDependency(info.pkg, d))
    : [];

  // ---- report ----
  console.log();
  console.log(unifiedDiff(target!.before, target!.after, target!.path.replace(info.root + "/", "")));
  if (info.rootFile !== target!.path && rootRes.wrapped) {
    console.log();
    console.log(unifiedDiff(rootBefore, rootRes.text, info.rootFile.replace(info.root + "/", "")));
  }
  if (vitePatch) {
    console.log();
    console.log(unifiedDiff(vitePatch.before, vitePatch.after, vitePatch.path.replace(info.root + "/", "")));
  }
  console.log();
  step(`new  ${c.dim("src/midnight.ts")}  (contract binding — add your deployed address)`);
  if (vitePatch) step(`new  ${c.dim("src/ws-shim.ts")}  (isomorphic-ws → browser WebSocket)`);
  step(src ? `copy ${c.dim(`src/managed/${recipe.circuit}/`)}  (compiled circuit + zk params)` : c.yellow(`compiled circuit "${recipe.circuit}" not found — compile it with \`compact\``));
  if (added) step(`dep  ${c.dim(`@midzap/sdk@${SDK_VERSION}`)}`);
  if (viteDeps.length) step(`dev  ${c.dim(viteDeps.join(", "))}`);

  if (opts.dryRun) {
    console.log();
    warn("--dry-run: nothing written.");
    return;
  }

  // ---- write ----
  save(target!.path, target!.after);
  if (info.rootFile !== target!.path && rootRes.wrapped) save(info.rootFile, rootRes.text);
  if (vitePatch) {
    save(vitePatch.path, vitePatch.after);
    if (!existsSync(vitePatch.shim)) save(vitePatch.shim, WS_SHIM);
  }
  if (!existsSync(cfgPath)) save(cfgPath, cfgText);
  if (src) {
    const dest = join(info.root, "src", "managed", recipe.circuit);
    mkdirSync(dirname(dest), { recursive: true });
    cpSync(src, dest, { recursive: true });
  }
  if (added) savePkg(info);

  console.log();
  ok(`${recipe.title} wired in.`);
  console.log(
    `\nNext:\n` +
      `  1. ${c.cyan("npm install")}\n` +
      `  2. fill in the getter TODO in ${c.dim(target!.path.replace(info.root + "/", ""))}\n` +
      `  3. deploy the circuit + set the address in ${c.dim("src/midnight.ts")} — see the @midzap/sdk README\n`
  );
}

function doctor(dir: string) {
  const info = loadProject(dir);
  const checks: [string, boolean][] = [];
  const allText = tsxFiles(info.root).map((f) => readFileSync(f, "utf8")).join("\n");
  checks.push(["@midzap/sdk in dependencies", !!info.pkg.dependencies?.["@midzap/sdk"]]);
  checks.push(["<MidnightZapProvider> present", allText.includes("<MidnightZapProvider")]);
  checks.push([
    "a predicate component used",
    /<Prove(Threshold|Membership|CredentialValid)/.test(allText),
  ]);
  checks.push(["src/midnight.ts present", existsSync(join(info.root, "src", "midnight.ts"))]);
  checks.push([
    "contract address set",
    existsSync(join(info.root, "src", "midnight.ts")) &&
      !readFileSync(join(info.root, "src", "midnight.ts"), "utf8").includes("0xREPLACE_WITH_DEPLOYED_ADDRESS"),
  ]);
  console.log();
  for (const [label, pass] of checks) console.log(`  ${pass ? c.green("✓") : c.red("✗")} ${label}`);
  const done = checks.every(([, p]) => p);
  console.log(`\n${done ? c.green("Ready for real proofs.") : c.yellow("Integration incomplete — see the ✗ items.")}`);
}

// ---- arg parsing ----
const argv = process.argv.slice(2);
const flags = new Set(argv.filter((a) => a.startsWith("-")));
const positional = argv.filter((a) => !a.startsWith("-"));
const [cmd, a1, a2] = positional;
const opts = { dryRun: flags.has("--dry-run"), yes: flags.has("--yes") || flags.has("-y") };

switch (cmd) {
  case "add":
    if (!a1) fail("Usage: midnightzap add <recipe> [dir]");
    add(a1, a2 ?? ".", opts);
    break;
  case "list":
    for (const r of Object.values(RECIPES)) console.log(`${c.cyan(r.id.padEnd(18))} ${r.title}`);
    break;
  case "doctor":
    doctor(a1 ?? ".");
    break;
  case undefined:
  case "help":
  case "--help":
    help();
    break;
  default:
    fail(`Unknown command "${cmd}". Run \`midnightzap help\`.`);
}
